name: dartmazing
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  bloc: ^7.1.0
  flutter_bloc: ^7.3.0
  provider: ^6.0.0
  equatable: ^2.0.3

  dartmazing_network:
    path: ../dartmazing_network
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  plugin:
    platforms:
      android:
        package: com.dartmazing_network
        pluginClass: DartmazingNetworkPlugin
      ios:
        pluginClass: DartmazingNetworkPlugin

flutter_intl:
  enabled: true
