name: dartmazing
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  cupertino_icons: ^0.1.3
  bloc: ^7.1.0
  flutter_bloc: ^7.1.0
  provider: ^5.0.0
  equatable: ^2.0.3

  dartmazing_network:
    path: ../dartmazing_network
  carousel_slider: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  module:
    androidPackage: com.dartmazing
    iosBundleIdentifier: com.dartmazing

flutter_intl:
  enabled: true
  main_locale: en_US

