name: dartmazing_network
description: A new flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.dartmazing_network
        pluginClass: DartmazingNetworkPlugin
      ios:
        pluginClass: DartmazingNetworkPlugin
    web:
        pluginClass: DartmazingNetworkWeb
        fileName: dartmazing_network_web.dart
